services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: api
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    image: api
    container_name: api
    command: uvicorn api:app --host 0.0.0.0 --port 5000 --reload
    environment:
      DATABASE_URL: "postgresql://user:pass@db:5432/api"
    ports:
      - "80:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db